version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: ./backend/.env

  backend:
    build: ./backend/
    env_file: ./backend/.env
    volumes:
      - media:/app/media/
      - static:/static/

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app/result_build/
      - static:/static/
  # frontend:
  #   env_file: ./backend/.env
  #   build: ./frontend/
  #   command: cp -r /app/build/. /static/
  #   volumes:
  #     - static:/static/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/media/
  # nginx:
  #   image: nginx:1.19.3
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./docs/:/usr/share/nginx/html/api/docs/
  #     - static:/static/
  #     - media:/media/
