version: '3.3'

volumes:
  pg_data_foodgram: {}
  static: {}
  media: {}

services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data
    env_file: ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: x9ilx/foodgram_backend
    env_file: ./.env
    volumes:
      - media:/app/media/
      - static:/static/
    depends_on:
      - db

  frontend:
    image: x9ilx/foodgram_frontend
    env_file: ./.env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static/

  nginx:
    image: x9ilx/foodgram_gateway
    ports:
      - "8000:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/sites-enabled/default
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/media/