# Generated by Django 3.2.3 on 2024-03-09 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='MeasurimentUnit',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=50, verbose_name='Наименование'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Measuriment unit',
                'verbose_name_plural': 'Measuriment units',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=200, verbose_name='Наименование'
                    ),
                ),
                (
                    'color',
                    models.CharField(
                        max_length=10, verbose_name='Цветовой код (HEX)'
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        unique=True, verbose_name='Уникальный slug'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=100, verbose_name='Наименование'
                    ),
                ),
                (
                    'measurement_unit',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='recipe.measurimentunit',
                        verbose_name='Единица измерения',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
            },
        ),
    ]
