# Generated by Django 3.2.3 on 2024-03-09 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipe_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(
                through='recipe.RecipeIngredients',
                to='recipe.Ingredient',
                verbose_name='Ингредиенты',
            ),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='ingredient',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ingredients',
                to='recipe.ingredient',
                verbose_name='Ингредиент',
            ),
        ),
        migrations.AddConstraint(
            model_name='recipeingredients',
            constraint=models.UniqueConstraint(
                fields=('recipe', 'ingredient'), name='recipe-ingredient'
            ),
        ),
    ]
