# Generated by Django 3.2.3 on 2024-03-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20240309_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(
                max_length=200, verbose_name='Наименование'
            ),
        ),
        migrations.AlterField(
            model_name='measurimentunit',
            name='name',
            field=models.CharField(
                max_length=200, verbose_name='Наименование'
            ),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(
                max_length=200, verbose_name='Наименование'
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(
                max_length=7, verbose_name='Цветовой код (HEX)'
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(
                max_length=200, unique=True, verbose_name='Уникальный slug'
            ),
        ),
    ]
